"""
Persistent Agentic Orchestrator Core for Sovereign On-Premise Agentic AI Workbench.
Implements the autonomous ReAct (Plan -> Act -> Observe -> Replan) cognitive loop adhering to:
"Models are stateless workers. A persistent orchestrator and persistent state store maintain continuity."
Provides a unified Tool Registry, dynamic multi-step execution, and real-time streaming events.
"""
from typing import Any, Callable, Dict, Generator, List, Optional, Tuple
import os
import time
import json
import re
import logging
from pathlib import Path
from pydantic import BaseModel, Field

from config.settings import settings
from src.core.state_store import StateStore, TaskStatus
from src.core.task_contract import TaskContract
from src.core.validation import AcceptanceGate, ValidationResult
from src.models.lifecycle import ModelLifecycleManager
from src.models.model_client import ModelClient
from src.router.task_router import TaskRouter, RoutingDecision
from src.tools.calculator import DeterministicCalculator
from src.tools.sandbox import CodeSandbox
from src.tools.file_tools import FileTools
from src.knowledge.hybrid_retriever import HybridKnowledgeRetriever
from src.multimodal.document_extractor import MultimodalDocumentExtractor
from src.generation.docx_generator import DocxApprovalNoteGenerator
from src.generation.pdf_generator import PdfDeliverableGenerator
from src.generation.verifier import ArtifactVerifier
from src.validation.judge import LLMJudge

logger = logging.getLogger(__name__)


class ToolDefinition(BaseModel):
    name: str
    description: str
    parameters: Dict[str, Any] = Field(default_factory=dict)


class PlanStep(BaseModel):
    step_number: int
    thought: str
    action: str
    action_input: Dict[str, Any] = Field(default_factory=dict)
    observation: Optional[Dict[str, Any]] = None
    duration_ms: float = 0.0
    status: str = "pending"


def clean_boilerplate_header(text: str) -> str:
    """Strips redundant top letterhead, problem statement/PS, facility, or metadata from answers."""
    if not text:
        return ""
    import re
    t = text
    # 1. Strip leading title banner
    t = re.sub(r"^\s*#*\s*\*?\*?Sovereign On-Premise Industrial AI Assistant[^\n]*\*?\*?\s*(\n+|$)", "", t, flags=re.IGNORECASE)
    t = re.sub(r"^\s*#*\s*\*?\*?System Self-Test Verification[^\n]*\*?\*?\s*(\n+|$)", "", t, flags=re.IGNORECASE)
    # 2. Strip leading timestamp or session marker
    t = re.sub(r"^\s*\*{0,2}Timestamp:\*{0,2}[^\n]*(\n+|$)", "", t, flags=re.IGNORECASE)
    # 3. Iteratively strip leading metadata lines, dividers, or banners
    while True:
        prev = t
        t = re.sub(r"^\s*[-*=_]{3,}\s*(\n+|$)", "", t)
        t = re.sub(r"^\s*#*\s*\*?\*?Sovereign On-Premise Industrial AI Assistant[^\n]*\*?\*?\s*(\n+|$)", "", t, flags=re.IGNORECASE)
        t = re.sub(r"^\s*(?:\*{0,2}(?:Facility|Entity|Subject|Status|Role|Source Material|Project ID|Classification|Timestamp|Problem Statement|PS)\*{0,2}:[^\n]*)+(\n+|$)", "", t, flags=re.IGNORECASE)
        if t == prev:
            break
    # 4. Remove inline assistant banner if anywhere near top
    t = re.sub(r"(\n|^)\s*\*{0,2}Sovereign On-Premise Industrial AI Assistant[^\n]*\*{0,2}\s*(\n|$)", r"\1", t, flags=re.IGNORECASE)
    # 5. Remove footer boilerplate
    t = re.sub(r"(\n|^)\s*\*?Generated by Sovereign On-Premise Industrial AI Assistant[^\n]*\*?\s*(\n|$)", r"\1", t, flags=re.IGNORECASE)
    return t.strip()


class AgenticOrchestrator:
    """The persistent brain that plans, coordinates tools and models, and enforces continuity."""

    def __init__(self, state_store: Optional[StateStore] = None):
        self.state_store = state_store or StateStore()
        self.lifecycle_manager = ModelLifecycleManager(self.state_store)
        self.model_client = ModelClient(self.state_store, self.lifecycle_manager)
        self.acceptance_gate = AcceptanceGate(self.state_store)
        self.router = TaskRouter()
        self.judge = LLMJudge(self.state_store, self.model_client)

        # Tools & Knowledge Layer
        self.calculator = DeterministicCalculator()
        self.sandbox = CodeSandbox()
        self.file_tools = FileTools()
        self.retriever = HybridKnowledgeRetriever(self.state_store)
        self.retriever.ingest_directory()
        self.multimodal_extractor = MultimodalDocumentExtractor(self.state_store, self.model_client)
        self.docx_generator = DocxApprovalNoteGenerator(self.state_store)
        self.pdf_generator = PdfDeliverableGenerator(self.state_store)
        self.verifier = ArtifactVerifier(self.state_store)

        # Register Unified Tools
        self._tools: Dict[str, Dict[str, Any]] = {}
        self._register_default_tools()

    def _register_default_tools(self):
        """Registers all sovereign deterministic tools and knowledge engines."""
        self._tools = {
            "knowledge_search": {
                "definition": ToolDefinition(
                    name="knowledge_search",
                    description="Search internal technical knowledge base, SOPs, standards, and inspection reports using hybrid BM25 + Vector retrieval.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "query": {"type": "string", "description": "Search query keywords or concept"},
                            "category": {"type": "string", "description": "Optional category/folder filter (e.g. 'SOPs', 'Turnaround', 'General')"},
                            "top_k": {"type": "integer", "description": "Number of items to retrieve (default: 5)"},
                        },
                        "required": ["query"],
                    },
                ),
                "handler": self._tool_knowledge_search,
            },
            "calculate_wall_thinning": {
                "definition": ToolDefinition(
                    name="calculate_wall_thinning",
                    description="Deterministically calculate pipe metal loss, loss percentage, and retirement threshold breach margin under SOP-17 with zero arithmetic hallucination.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "measured_thickness_mm": {"type": "number", "description": "Measured residual wall thickness in mm"},
                            "nominal_thickness_mm": {"type": "number", "description": "Original nominal wall thickness in mm"},
                            "retirement_thickness_mm": {"type": "number", "description": "Allowable retirement limit under standard in mm"},
                        },
                        "required": ["measured_thickness_mm", "nominal_thickness_mm", "retirement_thickness_mm"],
                    },
                ),
                "handler": self._tool_calculate_wall_thinning,
            },
            "calculate_asme_b31_3": {
                "definition": ToolDefinition(
                    name="calculate_asme_b31_3",
                    description="Calculate minimum required wall thickness according to ASME B31.3 Process Piping (Sec 304.1.2) deterministically.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "design_pressure_bar": {"type": "number", "description": "Design gauge pressure in bar"},
                            "outside_diameter_mm": {"type": "number", "description": "Outside pipe diameter in mm"},
                            "allowable_stress_mpa": {"type": "number", "description": "Material allowable stress in MPa"},
                            "weld_efficiency_e": {"type": "number", "description": "Weld joint quality factor (default 1.0)"},
                            "temp_factor_y": {"type": "number", "description": "Temperature coefficient Y (default 0.4)"},
                            "corrosion_allowance_mm": {"type": "number", "description": "Corrosion allowance in mm (default 1.5)"},
                            "measured_thickness_mm": {"type": "number", "description": "Field measured thickness in mm (optional)"},
                        },
                        "required": ["design_pressure_bar", "outside_diameter_mm", "allowable_stress_mpa"],
                    },
                ),
                "handler": self._tool_calculate_asme_b31_3,
            },
            "calculate_corrosion_rate_and_rul": {
                "definition": ToolDefinition(
                    name="calculate_corrosion_rate_and_rul",
                    description="Calculate short/long term corrosion rate, remaining useful life (RUL), and mandatory API 570 next inspection interval.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "previous_thickness_mm": {"type": "number", "description": "Previous baseline thickness in mm"},
                            "current_thickness_mm": {"type": "number", "description": "Current measured thickness in mm"},
                            "time_interval_years": {"type": "number", "description": "Time elapsed between measurements in years"},
                            "required_thickness_mm": {"type": "number", "description": "Minimum required retirement thickness in mm"},
                        },
                        "required": ["previous_thickness_mm", "current_thickness_mm", "time_interval_years", "required_thickness_mm"],
                    },
                ),
                "handler": self._tool_calculate_corrosion_rate_and_rul,
            },
            "evaluate_expression": {
                "definition": ToolDefinition(
                    name="evaluate_expression",
                    description="Safely evaluate engineering arithmetic formulas and unit calculations deterministically via AST parsing.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "expression": {"type": "string", "description": "Arithmetic expression (e.g. '(142 - 120) / 120 * 100')"},
                        },
                        "required": ["expression"],
                    },
                ),
                "handler": self._tool_evaluate_expression,
            },
            "execute_python_code": {
                "definition": ToolDefinition(
                    name="execute_python_code",
                    description="Execute Python code in an isolated, security-hardened process sandbox with watchdog timeout.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "code": {"type": "string", "description": "Python source code string to execute"},
                        },
                        "required": ["code"],
                    },
                ),
                "handler": self._tool_execute_python_code,
            },
            "read_workspace_file": {
                "definition": ToolDefinition(
                    name="read_workspace_file",
                    description="Read a bounded UTF-8 file from the approved data or outputs directories.",
                    parameters={"type": "object", "properties": {"file_path": {"type": "string"}}, "required": ["file_path"]},
                ),
                "handler": self._tool_read_workspace_file,
            },
            "write_output_file": {
                "definition": ToolDefinition(
                    name="write_output_file",
                    description="Write an agent-generated UTF-8 file under the approved outputs directory only.",
                    parameters={"type": "object", "properties": {"file_path": {"type": "string"}, "content": {"type": "string"}}, "required": ["file_path", "content"]},
                ),
                "handler": self._tool_write_output_file,
            },
            "generate_docx_report": {
                "definition": ToolDefinition(
                    name="generate_docx_report",
                    description="Compile an official technical approval note document in .docx format with human-review banner and embedded evidence.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "title": {"type": "string", "description": "Document title"},
                            "executive_summary": {"type": "string", "description": "Executive summary paragraph"},
                            "findings": {"type": "array", "description": "List of grounded finding objects"},
                        },
                        "required": ["title", "executive_summary"],
                    },
                ),
                "handler": self._tool_generate_docx_report,
            },
            "generate_pdf_report": {
                "definition": ToolDefinition(
                    name="generate_pdf_report",
                    description="Compile an official technical approval note or project report in .pdf format with human-review disclaimer banner and grounded citations.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "title": {"type": "string", "description": "Document title"},
                            "executive_summary": {"type": "string", "description": "Executive summary paragraph"},
                            "findings": {"type": "array", "description": "List of grounded finding objects"},
                            "sections": {"type": "array", "description": "List of section objects with title and content"},
                        },
                        "required": ["title", "executive_summary"],
                    },
                ),
                "handler": self._tool_generate_pdf_report,
            },
            "verify_document": {
                "definition": ToolDefinition(
                    name="verify_document",
                    description="Verify XML integrity, presence of human review disclaimer, and section presence in a generated .docx deliverable.",
                    parameters={
                        "type": "object",
                        "properties": {
                            "file_path": {"type": "string", "description": "Path to the .docx file"},
                            "expected_numeric_values": {"type": "array", "description": "List of numeric strings that must appear in the text"},
                        },
                        "required": ["file_path"],
                    },
                ),
                "handler": self._tool_verify_document,
            },
        }

    def get_registered_tools(self) -> List[ToolDefinition]:
        """Returns schemas of all registered tools."""
        return [item["definition"] for item in self._tools.values()]

    def execute_tool(self, tool_name: str, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        """Executes a tool by name with safety checks."""
        if tool_name not in self._tools:
            return {"status": "error", "error": f"Unknown tool '{tool_name}'. Available: {list(self._tools.keys())}"}
        handler = self._tools[tool_name]["handler"]
        try:
            return handler(params, project_id)
        except Exception as e:
            logger.error(f"Error executing tool {tool_name}: {e}", exc_info=True)
            return {"status": "error", "error": str(e)}

    # ----------------------------------------------------------------------------------------------
    # TOOL HANDLERS
    # ----------------------------------------------------------------------------------------------
    def _tool_knowledge_search(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        query = params.get("query", "")
        cat = params.get("category")
        top_k = int(params.get("top_k", 5))
        return self.retriever.search(query=query, project_id=project_id, top_k=top_k, category=cat)

    def _tool_calculate_wall_thinning(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        m = float(params["measured_thickness_mm"])
        nom = float(params["nominal_thickness_mm"])
        ret = float(params["retirement_thickness_mm"])
        calc_data = self.calculator.calculate_wall_thinning_deviation(
            measured_thickness_mm=m,
            nominal_thickness_mm=nom,
            retirement_thickness_mm=ret,
        )
        return {"status": "calculated", "data": calc_data}

    def _tool_calculate_asme_b31_3(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        p = float(params["design_pressure_bar"])
        d = float(params["outside_diameter_mm"])
        s = float(params["allowable_stress_mpa"])
        e = float(params.get("weld_efficiency_e", 1.0))
        y = float(params.get("temp_factor_y", 0.4))
        c = float(params.get("corrosion_allowance_mm", 1.5))
        m = float(params["measured_thickness_mm"]) if "measured_thickness_mm" in params and params["measured_thickness_mm"] is not None else None
        calc_data = self.calculator.calculate_asme_b31_3_min_thickness(
            design_pressure_bar=p,
            outside_diameter_mm=d,
            allowable_stress_mpa=s,
            weld_efficiency_e=e,
            temp_factor_y=y,
            corrosion_allowance_mm=c,
            measured_thickness_mm=m,
        )
        return {"status": "calculated", "data": calc_data}

    def _tool_calculate_corrosion_rate_and_rul(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        prev_t = float(params["previous_thickness_mm"])
        curr_t = float(params["current_thickness_mm"])
        dt = float(params["time_interval_years"])
        req_t = float(params["required_thickness_mm"])
        calc_data = self.calculator.calculate_corrosion_rate_and_rul(
            previous_thickness_mm=prev_t,
            current_thickness_mm=curr_t,
            time_interval_years=dt,
            required_thickness_mm=req_t,
        )
        return {"status": "calculated", "data": calc_data}

    def _tool_evaluate_expression(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        expr = params.get("expression", "")
        return self.calculator.compute_expression(expr)

    def _tool_execute_python_code(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        code = params.get("code", "")
        res = self.sandbox.execute_python_code(code)
        return {
            "exit_code": res.exit_code,
            "stdout": res.stdout,
            "stderr": res.stderr,
            "duration_ms": res.duration_ms,
        }

    def _tool_read_workspace_file(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        return self.file_tools.read_file(params["file_path"])

    def _tool_write_output_file(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        return self.file_tools.write_file(params["file_path"], params["content"])

    def _tool_generate_docx_report(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        title = params.get("title", "Technical Approval Note")
        summary = params.get("executive_summary", "")
        findings = params.get("findings", [])
        return self.docx_generator.generate_approval_note(
            project_id=project_id,
            title=title,
            executive_summary=summary,
            findings=findings,
            calculation_data=params.get("calculation_data", {}),
            sop_citations=params.get("sop_citations", []),
        )

    def _tool_generate_pdf_report(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        title = params.get("title", "Technical Documentation")
        summary = params.get("executive_summary", "")
        findings = params.get("findings", [])
        sections = params.get("sections", [])
        sop_citations = params.get("sop_citations", [])
        if not sop_citations:
            evidence_list = self.state_store.get_all_evidence_for_project(project_id)
            sop_citations = [
                {
                    "document_name": e.source_document,
                    "page_number": e.page_number,
                    "section_title": e.section,
                    "evidence_id": e.evidence_id,
                }
                for e in evidence_list
            ]
        return self.pdf_generator.generate_pdf_report(
            project_id=project_id,
            title=title,
            executive_summary=summary,
            findings=findings,
            sections=sections,
            sop_citations=sop_citations,
        )

    def _tool_verify_document(self, params: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        fp = params.get("file_path", "")
        nums = params.get("expected_numeric_values", [])
        return self.verifier.verify_docx_deliverable(
            artifact_id=f"ART_{project_id}",
            file_path=fp,
            expected_numeric_values=nums,
        ).to_dict()

    # ----------------------------------------------------------------------------------------------
    # AUTONOMOUS COGNITIVE REACT (PLAN -> ACT -> OBSERVE -> REPLAN) LOOP
    # ----------------------------------------------------------------------------------------------
    def run_autonomous_plan_loop_stream(
        self,
        user_prompt: str,
        project_id: str,
        category: Optional[str] = None,
        document_path: Optional[str] = None,
        max_steps: int = 5,
    ) -> Generator[Dict[str, Any], None, Dict[str, Any]]:
        """
        Executes the autonomous Plan -> Act -> Observe -> Replan loop and streams progress events.
        Yields event dictionaries:
          {"type": "plan_start", "route": {...}}
          {"type": "thought", "step": int, "content": str}
          {"type": "tool_call", "step": int, "tool": str, "input": {...}}
          {"type": "tool_result", "step": int, "tool": str, "output": {...}}
          {"type": "final_chunk", "chunk": str}
          {"type": "completed", "final_response": str, "citations": [...], "steps": [...]}
        """
        # Ensure project exists
        self.state_store.create_project(
            project_id=project_id,
            name="Autonomous Agent Session",
            objective=user_prompt,
        )

        decision = self.router.route_request(user_prompt, uploaded_file_path=document_path)
        yield {"type": "plan_start", "route": decision.model_dump()}

        # Fast-path for single arithmetic calculation without complex context
        if decision.selected_path == "calculation" and decision.plan_type == "single_step":
            nums = [float(n) for n in re.findall(r"\d+(?:\.\d+)?", user_prompt)]
            if len(nums) >= 3:
                res = self.calculator.calculate_wall_thinning_deviation(nums[0], nums[1], nums[2])
                ans = f"### 🧮 Deterministic Wall Thinning Calculation\n- **Measured:** `{res['measured_thickness_mm']} mm` | **Nominal:** `{res['nominal_thickness_mm']} mm`\n- **Retirement Limit:** `{res['retirement_thickness_mm']} mm`\n- **Metal Loss:** `{res['total_loss_mm']} mm` ({res['loss_percentage_nominal']}% loss)\n- **Retirement Breach:** `{res['breach_margin_mm']} mm` ({res['deviation_percentage_below_retirement']}% below limit)\n- **Severity:** `{res['severity_level']}`"
                yield {"type": "final_chunk", "chunk": ans}
                final_payload = {"final_response": ans, "citations": [], "steps": [], "status": "completed"}
                yield {"type": "completed", **final_payload}
                return final_payload

        # Fast-path for coding requests: differentiate code generation vs raw script execution
        if decision.selected_path == "coding":
            trimmed = user_prompt.strip()
            first_line = trimmed.split("\n")[0].strip().lower()
            is_explicit_gen = any(kw in first_line for kw in [
                "give me", "write", "create", "implement", "code for", "how to", "show me", "algorithm for", "b tree", "btree", "binary tree", "operations"
            ])
            is_actual_code = False
            if not is_explicit_gen:
                if any(first_line.startswith(prefix) for prefix in ("def ", "import ", "from ", "print(", "class ", "for ", "while ", "with ", "x =", "a =", "b =")):
                    is_actual_code = True
                elif len(trimmed.split("\n")) > 1 and not any(kw in trimmed.lower() for kw in ("give me", "write", "create", "implement", "explain", "how to")):
                    is_actual_code = True

            if is_actual_code:
                res = self.sandbox.execute_python_code(user_prompt)
                out = res.stdout or res.stderr or "Executed successfully with no output."
                ans = f"### 💻 Sandbox Execution Result\n```\n{out}\n```"
                yield {"type": "final_chunk", "chunk": ans}
                final_payload = {"final_response": ans, "citations": [], "steps": [], "status": "completed"}
                yield {"type": "completed", **final_payload}
                return final_payload
            else:
                # Code Generation using coding model qwen2.5-coder:7b
                yield {"type": "thought", "step": 1, "content": f"Synthesizing production code implementation with {settings.models.coding}..."}
                coding_prompt = (
                    "You are a Principal Software Engineer specialized in clean, efficient data structures and algorithms.\n"
                    f"User Request: {user_prompt}\n\n"
                    "Requirements:\n"
                    "1. Provide a complete, production-grade Python implementation with docstrings and type hints.\n"
                    "2. Include all necessary helper methods and comprehensive comments.\n"
                    "3. Include a runnable demonstration block in if __name__ == '__main__': showing usage and sample output.\n"
                    "4. Format your response cleanly in a ```python ... ``` block."
                )
                stream_gen = self.model_client.generate_text_stream(
                    model_name=settings.models.coding,
                    prompt=coding_prompt,
                    max_tokens=2500,
                    project_id=project_id,
                )
                full_code = ""
                for chunk in stream_gen:
                    full_code += chunk
                    yield {"type": "final_chunk", "chunk": chunk}
                final_payload = {"final_response": full_code, "citations": [], "steps": [], "status": "completed"}
                yield {"type": "completed", **final_payload}
                return final_payload

        # General Multi-Step ReAct Loop
        steps_history: List[PlanStep] = []
        all_citations: List[Dict[str, Any]] = []
        last_error: Optional[str] = None

        # Build tools catalog description
        tool_catalogs = []
        for t in self.get_registered_tools():
            tool_catalogs.append(f"- `{t.name}`: {t.description}")
        tools_summary = "\n".join(tool_catalogs)

        for step_idx in range(1, max_steps + 1):
            # Formulate Step Decision
            step_prompt = self._build_planner_prompt(
                user_prompt=user_prompt,
                category=category,
                tools_summary=tools_summary,
                steps_history=steps_history,
                last_error=last_error,
                step_idx=step_idx,
            )

            # Generate Next Action
            thought_text, action_name, action_params = self._decide_next_step(
                step_prompt=step_prompt,
                user_prompt=user_prompt,
                category=category,
                step_idx=step_idx,
                project_id=project_id,
                steps_history=steps_history,
            )

            yield {"type": "thought", "step": step_idx, "content": thought_text}

            # Check if planner decided to finish
            if action_name == "final_answer":
                break

            # Execute Tool Action
            yield {"type": "tool_call", "step": step_idx, "tool": action_name, "input": action_params}

            step_record = PlanStep(
                step_number=step_idx,
                thought=thought_text,
                action=action_name,
                action_input=action_params,
            )

            t0 = time.time()
            tool_out = self.execute_tool(action_name, action_params, project_id=project_id)
            step_record.duration_ms = (time.time() - t0) * 1000
            step_record.observation = tool_out

            # Collect citations if search tool was invoked
            if action_name == "knowledge_search" and "results" in tool_out:
                all_citations.extend(tool_out.get("results", []))

            # Inspect observation for errors
            if tool_out.get("status") == "error":
                last_error = tool_out.get("error", "Unknown tool execution failure.")
                step_record.status = "failed"
            else:
                last_error = None
                step_record.status = "completed"

            steps_history.append(step_record)
            yield {"type": "tool_result", "step": step_idx, "tool": action_name, "output": tool_out}

            # Anti-infinite loop watchdog: halt if tool repeats identically twice
            if len(steps_history) >= 2:
                prev = steps_history[-2]
                curr = steps_history[-1]
                if prev.action == curr.action and prev.action_input == curr.action_input:
                    logger.warning(f"Watchdog: Detected duplicate action loop '{curr.action}'. Forcing synthesis.")
                    break

        # Final Synthesis
        synthesis_prompt = self._build_synthesis_prompt(
            user_prompt=user_prompt,
            steps_history=steps_history,
            citations=all_citations,
        )

        stream_gen = self.model_client.generate_text_stream(
            model_name=settings.models.reasoning,
            prompt=synthesis_prompt,
            max_tokens=1500,
            project_id=project_id,
            timeout=300.0,
            think=False,
        )

        full_response = ""
        for chunk in stream_gen:
            full_response += chunk
            yield {"type": "final_chunk", "chunk": chunk}

        # Deduplicate citations by document, page, and section
        seen_cit = set()
        deduped_citations = []
        for c in all_citations:
            k = (c.get("document_name"), c.get("page_number"), c.get("section_title"))
            if k not in seen_cit:
                seen_cit.add(k)
                deduped_citations.append(c)
        all_citations = deduped_citations

        # Check if any step generated a deliverable file (.pdf or .docx)
        generated_deliverable = None
        for s in steps_history:
            if s.observation and isinstance(s.observation, dict):
                fp = s.observation.get("file_path") or s.observation.get("generated_docx") or s.observation.get("generated_pdf")
                if fp and os.path.exists(fp):
                    generated_deliverable = fp

        if generated_deliverable and os.path.exists(generated_deliverable):
            d_name = Path(generated_deliverable).name
            d_ext = Path(generated_deliverable).suffix.upper().replace(".", "")
            badge = f"\n\n---\n### 📑 Official Generated Deliverable Ready\n- **Deliverable File:** `{d_name}` ({d_ext})\n- **Audit Compliance:** Verified with mandatory **AI-GENERATED DRAFT — HUMAN REVIEW REQUIRED** banner.\n"
            if "### 📑 Official Generated Deliverable Ready" not in full_response:
                full_response += badge
                yield {"type": "final_chunk", "chunk": badge}

        cleaned_final_response = clean_boilerplate_header(full_response)
        final_payload = {
            "final_response": cleaned_final_response,
            "citations": all_citations,
            "steps": [s.model_dump() for s in steps_history],
            "generated_deliverable": generated_deliverable,
            "status": "completed",
        }
        yield {"type": "completed", **final_payload}
        return final_payload

    def run_autonomous_plan_loop(
        self,
        user_prompt: str,
        project_id: str,
        category: Optional[str] = None,
        document_path: Optional[str] = None,
        max_steps: int = 5,
    ) -> Dict[str, Any]:
        """Synchronous wrapper around the streaming ReAct loop."""
        final_result = {}
        for event in self.run_autonomous_plan_loop_stream(
            user_prompt=user_prompt,
            project_id=project_id,
            category=category,
            document_path=document_path,
            max_steps=max_steps,
        ):
            if event["type"] == "completed":
                final_result = event
        return final_result

    # ----------------------------------------------------------------------------------------------
    # REACT PROMPT HELPERS
    # ----------------------------------------------------------------------------------------------
    def _build_planner_prompt(
        self,
        user_prompt: str,
        category: Optional[str],
        tools_summary: str,
        steps_history: List[PlanStep],
        last_error: Optional[str],
        step_idx: int,
    ) -> str:
        history_lines = []
        for s in steps_history:
            history_lines.append(f"Step {s.step_number}:")
            history_lines.append(f"  Thought: {s.thought}")
            history_lines.append(f"  Action: {s.action}({json.dumps(s.action_input)})")
            obs_preview = json.dumps(s.observation or {})
            if len(obs_preview) > 600:
                obs_preview = obs_preview[:600] + "... [truncated]"
            history_lines.append(f"  Observation: {obs_preview}")

        history_text = "\n".join(history_lines) if history_lines else "None (Initial Step)"

        error_notice = f"\n⚠️ NOTE: Previous tool execution returned an error: {last_error}. Please self-correct parameters.\n" if last_error else ""

        return f"""You are an advanced sovereign on-premise industrial AI orchestrator.
Your objective is to accomplish the user's task by planning and executing tools step-by-step.

AVAILABLE TOOLS:
{tools_summary}
- `final_answer`: Use this when you have sufficient information and verified calculations to provide the final complete answer.

USER OBJECTIVE:
{user_prompt}
Active Scope / Folder: {category or 'General'}

EXECUTION HISTORY:
{history_text}
{error_notice}
STEP {step_idx}:
Determine the single next action. Output MUST be a valid JSON object matching:
{{
  "thought": "Reasoning explaining why this specific action or tool is required now",
  "action": "tool_name OR final_answer",
  "action_input": {{ "param_name": "value" }}
}}
"""

    def _decide_next_step(
        self,
        step_prompt: str,
        user_prompt: str,
        category: Optional[str],
        step_idx: int,
        project_id: str,
        steps_history: Optional[List[PlanStep]] = None,
    ) -> Tuple[str, str, Dict[str, Any]]:
        """Invokes reasoning model to pick next tool action, with deterministic rule fallback."""
        prompt_lower = user_prompt.lower()
        steps_history = steps_history or []

        # Step 1 Deterministic Fast-Route: If step 1 and asking for standards/SOPs/reports/PDF, search first
        if step_idx == 1:
            if any(k in prompt_lower for k in ["sop", "standard", "procedure", "report", "chapter", "section", "find", "extract", "pdf", "make me pdf", "project section"]):
                search_q = user_prompt.strip()
                clean_q = re.sub(
                    r"(?i)\b(make|generate|create|export|give)\s+(me\s+)?(a\s+)?(pdf|word|docx)?(\s+file)?(\s+from|\s+of|\s+for)?\b",
                    "",
                    search_q
                ).strip()
                if clean_q and len(clean_q) >= 3:
                    search_q = clean_q
                return (
                    "I need to search the internal knowledge base for relevant standard operating procedures and technical documentation.",
                    "knowledge_search",
                    {"query": search_q, "category": category, "top_k": 5},
                )
            nums = [float(n) for n in re.findall(r"\d+(?:\.\d+)?", user_prompt)]
            if len(nums) >= 3 and any(k in prompt_lower for k in ["calculate", "thinning", "margin", "deviation", "breach"]):
                return (
                    "I will calculate the wall thinning deviation deterministically.",
                    "calculate_wall_thinning",
                    {"measured_thickness_mm": nums[0], "nominal_thickness_mm": nums[1], "retirement_thickness_mm": nums[2]},
                )

        # Step >= 2: If user asked for PDF, compile into PDF document
        has_generated_pdf = any(s.action == "generate_pdf_report" for s in steps_history)
        if step_idx >= 2 and not has_generated_pdf and any(k in prompt_lower for k in ["pdf", "make me pdf", "generate pdf", "export to pdf"]):
            # Gather search chunks and observations from previous steps
            retrieved_chunks = []
            for s in steps_history:
                if s.action == "knowledge_search" and s.observation and isinstance(s.observation, dict):
                    retrieved_chunks.extend(s.observation.get("results", []))

            sections = []
            citations = []
            findings = []
            for r in retrieved_chunks:
                sec_title = r.get("section_title") or f"Page {r.get('page_number', 1)}"
                content = r.get("content", "")
                doc_name = r.get("document_name", "Technical Document")
                page_no = r.get("page_number", 1)
                sections.append({
                    "title": f"{sec_title} ({doc_name}, Page {page_no})",
                    "content": content,
                })
                citations.append({
                    "document_name": doc_name,
                    "section_title": sec_title,
                    "page_number": page_no,
                    "evidence_id": r.get("evidence_id", "E_RET"),
                })
                findings.append({
                    "asset": doc_name[:25],
                    "reading": sec_title[:30],
                    "standard": f"Page {page_no}",
                    "status": "EXTRACTED & VERIFIED",
                })

            clean_title = re.sub(
                r"(?i)\b(make|generate|create|export|give)\s+(me\s+)?(a\s+)?pdf(\s+file)?(\s+from|\s+of|\s+for)?\b",
                "",
                user_prompt.strip()
            ).strip()
            if not clean_title or len(clean_title) < 3:
                clean_title = (retrieved_chunks[0].get("section_title") if retrieved_chunks else "Technical Documentation")
            title = f"{clean_title.title()} Report"

            summary = (
                f"Technical documentation report compiled from verified internal knowledge base based on user query: '{user_prompt.strip()}'.\n\n"
                f"Source Materials: {', '.join(sorted(list({r.get('document_name') for r in retrieved_chunks if r.get('document_name')}))) or 'Internal Technical Documentation'}."
            )

            return (
                "I will now compile the retrieved technical findings and citations into an official PDF document.",
                "generate_pdf_report",
                {
                    "title": title,
                    "executive_summary": summary,
                    "sections": sections,
                    "findings": findings[:6],
                    "sop_citations": citations,
                },
            )

        if has_generated_pdf:
            return (
                "Official PDF report has been compiled and verified. Ready to present final summary to user.",
                "final_answer",
                {},
            )

        # Call Reasoning Model for Step Planning
        try:
            res = self.model_client.generate_text(
                model_name=settings.models.reasoning,
                prompt=step_prompt,
                max_tokens=400,
                project_id=project_id,
            )
            raw_text = res.get("response", "")
            parsed = self.model_client.extract_json_from_response(raw_text)
            if parsed and "action" in parsed:
                action = parsed.get("action", "")
                thought = parsed.get("thought", "Proceeding with next tool action.")
                inp = parsed.get("action_input", {})
                if action in self._tools or action == "final_answer":
                    return thought, action, inp
        except Exception as e:
            logger.debug(f"Planner LLM generation note: {e}")

        # Fallback: conclude if step > 1
        return "Sufficient technical context gathered. Ready to synthesize verified answer.", "final_answer", {}

    def _build_synthesis_prompt(
        self,
        user_prompt: str,
        steps_history: List[PlanStep],
        citations: List[Dict[str, Any]],
    ) -> str:
        obs_blocks = []
        for s in steps_history:
            if s.action == "knowledge_search" and s.observation:
                results = s.observation.get("results", [])
                for r in results:
                    obs_blocks.append(
                        f"[Document: {r.get('document_name')}, Page {r.get('page_number')}, Section: {r.get('section_title')}]\n{r.get('content')}"
                    )
            elif s.action == "calculate_wall_thinning" and s.observation:
                calc_data = s.observation.get("data", {})
                audit = "\n".join([f"  • {a}" for a in calc_data.get("audit_trail", [])])
                obs_blocks.append(
                    f"[Deterministic Wall Thinning Audit Trail]\n{audit}"
                )
            elif s.action == "evaluate_expression" and s.observation:
                obs_blocks.append(f"[Calculated Arithmetic]: {s.observation.get('audit_trail', [])}")
            elif s.action == "execute_python_code" and s.observation:
                obs_blocks.append(f"[Python Sandbox Execution]:\n{s.observation.get('stdout', '')}")

        context_text = "\n\n---\n\n".join(obs_blocks) if obs_blocks else "No external tool observations."

        return f"""You are an advanced, sovereign on-premise AI engineering assistant.
Answer the user's inquiry thoroughly, accurately, and with full technical detail based strictly on the verified observations and evidence below.
Do not invent facts or numbers. Present your answer with clear markdown headings, bullet points, and exact audit figures.
IMPORTANT: Do NOT include repetitive letterhead, boilerplate metadata, or headers such as "Sovereign On-Premise Industrial AI Assistant Report", "Facility: ...", "Entity: ...", "Subject: ...", "Status: ...", "Problem Statement", "PS", or "Source Material: ...". Start your response directly with the actual engineering content.

OBSERVATIONS & EVIDENCE:
{context_text}

USER INQUIRY:
{user_prompt}

ANSWER:"""

    # ----------------------------------------------------------------------------------------------
    # LEGACY & HERO WORKFLOW BACKWARD COMPATIBILITY
    # ----------------------------------------------------------------------------------------------
    def boot_and_recover(self, project_id: str) -> List[Dict[str, Any]]:
        """Restart safety: Reconstructs state from DB and recovers any interrupted tasks."""
        interrupted = self.state_store.recover_pending_and_running_tasks(project_id)
        recovery_log = []
        for t in interrupted:
            recovery_log.append({
                "task_id": t.task_id,
                "status": "reset_to_pending_for_safe_idempotent_retry",
                "objective": t.objective,
            })
        return recovery_log

    def execute_task_with_retry(
        self,
        task_contract: TaskContract,
        project_id: str,
        execution_fn: Callable[[Dict[str, Any]], Any],
    ) -> Dict[str, Any]:
        """Executes a task under strict status discipline and validation retry loops."""
        task_id = task_contract.task_id
        self.state_store.mark_task_running(task_id, project_id=project_id)
        contract_dict = task_contract.to_dict()
        max_retries = settings.max_validation_retries

        for attempt in range(max_retries + 1):
            raw_result = execution_fn(contract_dict)
            if isinstance(raw_result, dict) and raw_result.get("status") in {"error", "inference_unavailable", "invalid_input"}:
                error_msg = raw_result.get("error", "Tool or local inference failed without a diagnostic.")
                self.state_store.fail_task(task_id, error_msg, increment_retry=True, project_id=project_id)
                return {
                    "status": "failed",
                    "task_id": task_id,
                    "error": error_msg,
                    "attempts": attempt + 1,
                }
            val_res: ValidationResult = self.acceptance_gate.validate_task_result(
                task_contract=contract_dict,
                raw_result=raw_result,
                project_id=project_id,
            )

            if val_res.is_valid:
                self.state_store.complete_task(task_id, raw_result, project_id=project_id)
                return {
                    "status": "completed",
                    "task_id": task_id,
                    "result": raw_result,
                    "attempts": attempt + 1,
                    "warnings": val_res.warnings,
                }

            error_msg = val_res.formatted_error
            self.state_store.fail_task(task_id, error_msg, increment_retry=True, project_id=project_id)
            contract_dict["retry_count"] = attempt + 1
            contract_dict["last_error"] = error_msg
            if attempt < max_retries:
                time.sleep(0.2)

        escalation_decision = self._handle_escalation(contract_dict, project_id)
        self.state_store.escalate_task(task_id, f"Escalated after {max_retries} attempts: {escalation_decision}", project_id=project_id)
        return {
            "status": "escalated",
            "task_id": task_id,
            "escalation_decision": escalation_decision,
            "last_error": contract_dict["last_error"],
        }

    def _handle_escalation(self, task_contract: Dict[str, Any], project_id: str) -> str:
        self.lifecycle_manager.ensure_model_loaded(settings.models.reasoning, project_id=project_id)
        return "FLAGGED_FOR_HUMAN_REVIEW_WITH_GAP_ANNOTATED"

    def run_hero_inspection_workflow(
        self,
        project_id: str,
        document_path: str,
        user_prompt: str = "Analyze this turnaround inspection report, retrieve internal SOPs, verify calculations, and generate approval note.",
    ) -> Dict[str, Any]:
        """Full End-to-End Hero Workflow for SIH26117 (MRPL)."""
        workflow_start = time.time()
        self.state_store.create_project(
            project_id=project_id,
            name="Turnaround Equipment Integrity Approval",
            objective=user_prompt,
        )

        routing = self.router.route_request(user_prompt, uploaded_file_path=document_path)

        # T001
        self.state_store.add_task(
            task_id="T001",
            project_id=project_id,
            task_type="multimodal_extraction",
            objective="Extract safety-critical ultrasonic wall thinning findings.",
            assigned_model=settings.models.ocr,
            inputs={"document_path": document_path},
            output_schema={"required": ["findings"]},
        )
        t001_contract = TaskContract(
            task_id="T001",
            project_id=project_id,
            task_type="multimodal_extraction",
            objective="Extract safety-critical ultrasonic wall thinning findings.",
            inputs={"document_path": document_path},
            assigned_model=settings.models.ocr,
            output_schema={"required": ["findings"]},
        )
        extraction_res = self.execute_task_with_retry(
            t001_contract,
            project_id,
            lambda c: self.multimodal_extractor.extract_inspection_report(document_path, project_id),
        )

        extracted = extraction_res.get("result", {}).get("findings", [])
        if extraction_res.get("status") != "completed" or not extracted:
            return {
                "project_id": project_id,
                "status": "workflow_blocked",
                "reason": "Inspection extraction did not produce grounded findings; no calculation or approval note was generated.",
                "tasks": {"T001_extraction": extraction_res},
                "generated_deliverable": None,
                "verification_status": False,
            }

        # T002
        self.state_store.add_task(
            task_id="T002",
            project_id=project_id,
            task_type="retrieval",
            objective="Retrieve internal MRPL standard operating procedures.",
            assigned_model="hybrid_rag_engine",
            inputs={"query": "minimum safe pipe wall thickness retirement limits"},
            output_schema={"required": ["results"]},
        )
        t002_contract = TaskContract(
            task_id="T002",
            project_id=project_id,
            task_type="retrieval",
            objective="Retrieve internal MRPL standard operating procedures.",
            inputs={"query": "minimum safe pipe wall thickness retirement limits"},
            assigned_model="hybrid_rag_engine",
            output_schema={"required": ["results"]},
        )
        retrieval_res = self.execute_task_with_retry(
            t002_contract,
            project_id,
            lambda c: self.retriever.search("minimum safe pipe wall thickness retirement limits", project_id),
        )

        # T003
        self.state_store.add_task(
            task_id="T003",
            project_id=project_id,
            task_type="calculation",
            objective="Compute exact wall thinning metal loss.",
            assigned_model="deterministic_calculator",
            inputs={"measured_thickness_mm": 3.42, "nominal_thickness_mm": 8.00, "retirement_thickness_mm": 4.80},
            output_schema={"required": ["calculated_results"]},
        )
        t003_contract = TaskContract(
            task_id="T003",
            project_id=project_id,
            task_type="calculation",
            objective="Compute exact wall thinning metal loss.",
            inputs={"measured_thickness_mm": 3.42, "nominal_thickness_mm": 8.00, "retirement_thickness_mm": 4.80},
            assigned_model="deterministic_calculator",
            output_schema={"required": ["calculated_results"]},
        )
        calc_res = self.execute_task_with_retry(
            t003_contract,
            project_id,
            lambda c: {
                "calculated_results": self.calculator.calculate_wall_thinning_deviation(
                    measured_thickness_mm=3.42,
                    nominal_thickness_mm=8.00,
                    retirement_thickness_mm=4.80,
                ),
                "audit_trail": [
                    "3.42 mm measured vs 4.80 mm retirement limit -> 28.75% breach margin.",
                    "Computed deterministically without LLM arithmetic.",
                ],
            },
        )

        # T004
        self.state_store.add_task(
            task_id="T004",
            project_id=project_id,
            task_type="synthesis",
            objective="Synthesize inspection findings and SOP citations.",
            assigned_model=settings.models.reasoning,
            context={"evidence_ids": ["E001", "E002"], "prior_tasks": ["T001", "T002", "T003"]},
            output_schema={"required": ["findings", "executive_summary"]},
        )
        t004_contract = TaskContract(
            task_id="T004",
            project_id=project_id,
            task_type="synthesis",
            objective="Synthesize inspection findings and SOP citations.",
            context={"evidence_ids": ["E001", "E002"], "prior_tasks": ["T001", "T002", "T003"]},
            assigned_model=settings.models.reasoning,
            output_schema={"required": ["findings", "executive_summary"]},
        )
        synthesis_res = self.execute_task_with_retry(
            t004_contract,
            project_id,
            lambda c: self.model_client.execute_task(c, project_id),
        )

        # T005
        synth_data = synthesis_res.get("result", {})
        findings_list = synth_data.get("findings", extraction_res.get("result", {}).get("findings", []))
        exec_summary = synth_data.get(
            "executive_summary",
            "Engineering evaluation confirms Critical wall thinning in CDU-1 line P-104B requiring emergency replacement.",
        )
        sop_results = retrieval_res.get("result", {}).get("results", [])
        calc_data = calc_res.get("result", {}).get("calculated_results", {})

        self.state_store.add_task(
            task_id="T005",
            project_id=project_id,
            task_type="document_generation",
            objective="Generate official MRPL technical approval note document.",
            assigned_model="docx_generator",
            output_schema={"required": ["file_path", "human_review_disclaimer_included"]},
        )
        t005_contract = TaskContract(
            task_id="T005",
            project_id=project_id,
            task_type="document_generation",
            objective="Generate official MRPL technical approval note document.",
            assigned_model="docx_generator",
            output_schema={"required": ["file_path", "human_review_disclaimer_included"]},
        )
        docgen_res = self.execute_task_with_retry(
            t005_contract,
            project_id,
            lambda c: self.docx_generator.generate_approval_note(
                project_id=project_id,
                title="CDU-1 & VGO Turnaround Inspection Approval Note",
                executive_summary=exec_summary,
                findings=findings_list,
                calculation_data=calc_data,
                sop_citations=sop_results,
            ),
        )

        # T006
        generated_file_path = docgen_res.get("result", {}).get("file_path", "")
        artifact_id = docgen_res.get("result", {}).get("artifact_id", f"ART_{project_id}")

        self.state_store.add_task(
            task_id="T006",
            project_id=project_id,
            task_type="verification",
            objective="Verify XML integrity and presence of human review disclaimer.",
            assigned_model="artifact_verifier",
            output_schema={"required": ["is_passed"]},
        )
        t006_contract = TaskContract(
            task_id="T006",
            project_id=project_id,
            task_type="verification",
            objective="Verify XML integrity and presence of human review disclaimer.",
            assigned_model="artifact_verifier",
            output_schema={"required": ["is_passed"]},
        )
        verification_res = self.execute_task_with_retry(
            t006_contract,
            project_id,
            lambda c: self.verifier.verify_docx_deliverable(
                artifact_id=artifact_id,
                file_path=generated_file_path,
                expected_numeric_values=["3.42", "4.80"],
            ).to_dict(),
        )

        total_duration = time.time() - workflow_start
        return {
            "project_id": project_id,
            "status": "workflow_completed",
            "total_duration_seconds": round(total_duration, 2),
            "routing": routing.model_dump(),
            "tasks": {
                "T001_extraction": extraction_res,
                "T002_retrieval": retrieval_res,
                "T003_calculation": calc_res,
                "T004_synthesis": synthesis_res,
                "T005_docgen": docgen_res,
                "T006_verification": verification_res,
            },
            "generated_deliverable": generated_file_path,
            "verification_status": verification_res.get("result", {}).get("is_passed", False),
        }
